default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] || 'user' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'password' %>
  host: <%= ENV['POSTGRES_HOST'] || 'db' %>
  port: 5432
  pool: 5

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  primary:
    <<: *default
    database: myapp_production
  cable:
    <<: *default
    database: myapp_production