default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'password' %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  port: 5432
  pool: 5

development:
  <<: *default
  database: donate_chat_development

test:
  <<: *default
  database: donate_chat_test

production:
  primary:
    <<: *default
    database: donate_chat_production

  cable:
    <<: *default
    database: donate_chat_production

  queue:
    <<: *default
    database: donate_chat_production